version: '3'
services:
  module-account:
    build: .
    ports:
      - "8081:8081"
  module-order-history:
    build: .
    ports:
      - "8082:8082"
  module-main:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - module-account
      - module-order-history


